# Generated by Django 5.2.6 on 2025-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
