# Generated by Django 5.2.6 on 2025-10-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_certificatemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
    ]
